In [ ]:
#importing
import numpy as np

In [ ]:
#creating 1d array
A=np.array([2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#creating 2d array
B=np.array([[2,3,4],[7,8,9,]])
print(B)

[[2 3 4]
 [7 8 9]]


In [ ]:
C=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(C)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
e=np.ones((3,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
e=np.ones((2,3,2))
print(e)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
g=np.zeros((3,2))
print(g)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
g=np.zeros((2,3,2))
print(g)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
i=np.eye(4,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
#arange
j=np.arange(3,31,3)
print(j)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#arange
H=np.arange(4,41,4).reshape(5,2)
print(H)

[[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]


In [ ]:
k=np.arange(5,1001,5).reshape(25,8)
print(k)

[[   5   10   15   20   25   30   35   40]
 [  45   50   55   60   65   70   75   80]
 [  85   90   95  100  105  110  115  120]
 [ 125  130  135  140  145  150  155  160]
 [ 165  170  175  180  185  190  195  200]
 [ 205  210  215  220  225  230  235  240]
 [ 245  250  255  260  265  270  275  280]
 [ 285  290  295  300  305  310  315  320]
 [ 325  330  335  340  345  350  355  360]
 [ 365  370  375  380  385  390  395  400]
 [ 405  410  415  420  425  430  435  440]
 [ 445  450  455  460  465  470  475  480]
 [ 485  490  495  500  505  510  515  520]
 [ 525  530  535  540  545  550  555  560]
 [ 565  570  575  580  585  590  595  600]
 [ 605  610  615  620  625  630  635  640]
 [ 645  650  655  660  665  670  675  680]
 [ 685  690  695  700  705  710  715  720]
 [ 725  730  735  740  745  750  755  760]
 [ 765  770  775  780  785  790  795  800]
 [ 805  810  815  820  825  830  835  840]
 [ 845  850  855  860  865  870  875  880]
 [ 885  890  895  900  905  910  915  920]
 [ 925  930

In [ ]:
v=np.linspace(1,2,6)
print(v)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
l=np.arange(1,7).reshape(2,3)
print(l)

[[1 2 3]
 [4 5 6]]


In [ ]:
p=np.arange(1,7).reshape(2,3)
print(p)
b=np.arange(9,15).reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
print(p+b)

[[10 12 14]
 [16 18 20]]


In [ ]:
d=np.sum((p,b))
print(d)

90


In [ ]:
x=np.sum((p,b),axis=0)
print(x)

[[10 12 14]
 [16 18 20]]


In [ ]:
x=np.sum((p,b),axis=2)
print(x)

[[ 6 15]
 [30 39]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=1))

[[4. 4.]
 [4. 4.]]


In [ ]:
a=np.array([[7,4],[4,7]])
b=np.array([[8,9],[9,8]])
print(a*b)

[[56 36]
 [36 56]]


In [ ]:
print(a@b)

[[92 95]
 [95 92]]


In [ ]:
b=np.array[25,289,361,81]#find square roots and iterate through result values output:5 square is 25

In [ ]:
 b=np.array([25,289,361,81])
 for i in b:
  print(np.sqrt(i),"square is",i)


5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


In [ ]:
a=np.array([34,35,36,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[34 35 36]
 [36 37 38]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [36 37 38  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("\n")
print(np.dstack(a))
#number of rows becomes number of coloums
#coloums become rows
#group become coloums

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
