In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
a=np.random.rand(8,4) #rand-range between 0 and 1
print(a)

[[0.34123981 0.23945536 0.40887908 0.97933897]
 [0.46208727 0.2345325  0.59584348 0.56848945]
 [0.56231045 0.4809855  0.53921733 0.77965444]
 [0.71339403 0.10245156 0.57159547 0.16344499]
 [0.71208578 0.37090658 0.57908179 0.96244154]
 [0.79647067 0.3064511  0.76721246 0.48291048]
 [0.09563434 0.65688868 0.32654041 0.64951903]
 [0.10874417 0.28127498 0.13910239 0.41231568]]


In [ ]:
b=np.random.rand(1)
print(b)

[0.01865726]


In [ ]:
a=10*np.random.rand(8,4) #rand-range between 0 and 1
print(a)

[[3.94010708 6.68889834 9.87384097 0.60958334]
 [6.1601504  1.78777993 6.90413171 3.07613534]
 [3.78470841 3.09219883 6.66271399 3.06617632]
 [6.95271213 4.74428881 7.35931212 7.07639286]
 [9.21803385 4.24880637 1.50799458 5.39683912]
 [7.06616177 9.78797335 0.15578956 0.94972183]
 [3.24461413 3.68480536 8.37782118 9.22725991]
 [5.21246235 8.41129372 3.30555139 0.32008586]]


In [ ]:
a=np.floor(10*np.random.rand(8,4)) #rand-range between 0 and 1
print(a)

[[8. 2. 5. 2.]
 [4. 2. 0. 3.]
 [1. 5. 0. 6.]
 [4. 2. 8. 2.]
 [2. 9. 9. 4.]
 [2. 7. 1. 3.]
 [0. 2. 2. 4.]
 [5. 7. 0. 0.]]


In [ ]:
c=np.arange(1,33).reshape(8,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(a,4)

[array([[8., 2., 5., 2.],
        [4., 2., 0., 3.]]),
 array([[1., 5., 0., 6.],
        [4., 2., 8., 2.]]),
 array([[2., 9., 9., 4.],
        [2., 7., 1., 3.]]),
 array([[0., 2., 2., 4.],
        [5., 7., 0., 0.]])]

In [ ]:
np.vsplit(a,(4,7))

[array([[8., 2., 5., 2.],
        [4., 2., 0., 3.],
        [1., 5., 0., 6.],
        [4., 2., 8., 2.]]),
 array([[2., 9., 9., 4.],
        [2., 7., 1., 3.],
        [0., 2., 2., 4.]]),
 array([[5., 7., 0., 0.]])]

In [ ]:
np.vsplit(a,(3,5))   #split it after third row

[array([[8., 2., 5., 2.],
        [4., 2., 0., 3.],
        [1., 5., 0., 6.]]),
 array([[4., 2., 8., 2.],
        [2., 9., 9., 4.]]),
 array([[2., 7., 1., 3.],
        [0., 2., 2., 4.],
        [5., 7., 0., 0.]])]

In [ ]:
np.vsplit(a,(8,4))

[array([[8., 2., 5., 2.],
        [4., 2., 0., 3.],
        [1., 5., 0., 6.],
        [4., 2., 8., 2.],
        [2., 9., 9., 4.],
        [2., 7., 1., 3.],
        [0., 2., 2., 4.],
        [5., 7., 0., 0.]]),
 array([], shape=(0, 4), dtype=float64),
 array([[2., 9., 9., 4.],
        [2., 7., 1., 3.],
        [0., 2., 2., 4.],
        [5., 7., 0., 0.]])]

In [ ]:
np.vsplit(a,(3,7))

[array([[8., 2., 5., 2.],
        [4., 2., 0., 3.],
        [1., 5., 0., 6.]]),
 array([[4., 2., 8., 2.],
        [2., 9., 9., 4.],
        [2., 7., 1., 3.],
        [0., 2., 2., 4.]]),
 array([[5., 7., 0., 0.]])]

In [ ]:
np.pi    #trigonometry

3.141592653589793

In [ ]:
h=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(h)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(h)  #convert radius to degree

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(h)  #convert degree to radius

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.sin(0.785) #radius

0.706825181105366

In [ ]:
np.cos(0)

1.0

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(45)

1.6197751905438615

In [ ]:
np.tan(0)

0.0

In [ ]:
np.tan(90)

-1.995200412208242

In [ ]:
#Statistics
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
r=np.arange(1,5).reshape(2,2)
print(r)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(r)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
r=np.arange(1,25).reshape(6,4)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(r))

23


In [ ]:
r=np.floor(10*np.random.rand(24)).reshape(6,4)
print(r)


[[0. 9. 4. 5.]
 [6. 6. 2. 5.]
 [9. 0. 3. 2.]
 [9. 8. 2. 7.]
 [0. 9. 7. 3.]
 [2. 4. 3. 3.]]


In [ ]:
print(np.argmax(r))

1


In [ ]:
print(np.argmax(r,axis=0))

[2 0 4 3]


In [ ]:
print(np.argmax(r,axis=1))

[1 0 0 0 1 1]


In [ ]:
print(np.argmin(r))

0


In [ ]:
print(np.argmin(r,axis=0))

[0 2 1 2]


In [ ]:
print(np.argmin(r,axis=1))

[0 2 1 2 0 0]


In [ ]:
#Searching
v=np.array([34,25,27,47,74,88])
print(np.where(v%2==0))
print(np.where(v/2==0))

(array([0, 4, 5]),)
(array([], dtype=int64),)


In [ ]:
e=np.array([24,16,7,17,54,60])     #check index
print(np.where(e%6==0))

(array([0, 4, 5]),)


In [ ]:
q=np.array([7,8,9,10,11])
print(np.searchsorted(q,5))

0


In [ ]:
q=np.array([4,1,7,8,9,3])
print(np.searchsorted(q,1))

0


In [ ]:
import numpy as np #sorting array

In [ ]:
arr=np.array(['banana','apple','cherry'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr=np.array(['true','false','true'])
print(np.sort(arr))

['false' 'true' 'true']


In [ ]:
#2d sort -sorting happens with in row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr=np.array([40,43,50,44,67,78])       #filtering
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr=np.array([40,49,30,47,57,98])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 5]),)


In [ ]:
names=np.array(["narasimha","nagesh","ganesh","dheeraj","vamsi"])
initials=np.array(["g","g","p","t","p"])
for i,j in zip(initials,names):
  print(i,",",j)

g , narasimha
g , nagesh
p , ganesh
t , dheeraj
p , vamsi


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divide(a1,a2)
print(n)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.mod(a1,a2)
print(n)

[10 20  8 17  2 10]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:
#logarithms
a1=np.arange(2,10)
print(a1)
print(np.log2(a1))

[2 3 4 5 6 7 8 9]
[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log(a))   #natural log e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a))   #log base 2

0.2630344058337938


In [ ]:
a=2.2
print(np.log10(a))   #log base 10

0.3424226808222063


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a))  #natural log e

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
#other mathematical statements
a1=np.array([10,15,25,15])     #e2-e1
newarr=np.diff(a1)
print(newarr)

[  5  10 -10]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a2=np.array([10,15,20,25,30])
x=np.cumsum(a2)
print(x)

[ 10  25  45  70 100]


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a)    #Reduce function takes multiple inputs give single output
print(gc)

3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a)    #Reduce function takes multiple inputs give single output
print(lc)

60
